name: CICD
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
on:
  pull_request:
  push:
    branches:
      - master
      - development
  jobs:
    echo_github_events:
      name: echo github events
      runs-on: ubuntu-latest
      steps:
        - name: Echo test
          run: echo Hello world!
        - name: Echo github ref #The branch or tag ref that triggered the workflow run.
          run: echo ${{ github.ref }}
        - name: Echo github head ref # Only available on PULL_REQUEST, prints source branch of pull request
          run: echo ${{ github.head_ref }}
        - name: Echo github base ref (target branch) # Only available on PULL_REQUEST, prints target branch of pull request
          run: echo ${{ github.base_ref }}
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        - name: Dump job context
          env:
            JOB_CONTEXT: ${{ toJson(job) }}
          run: echo "$JOB_CONTEXT"
        - name: Dump steps context
          env:
            STEPS_CONTEXT: ${{ toJson(steps) }}
          run: echo "$STEPS_CONTEXT"
        - name: Dump runner context
          env:
            RUNNER_CONTEXT: ${{ toJson(runner) }}
          run: echo "$RUNNER_CONTEXT"
        - name: Dump strategy context
          env:
            STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          run: echo "$STRATEGY_CONTEXT"
        - name: Dump matrix context
          env:
            MATRIX_CONTEXT: ${{ toJson(matrix) }}
          run: echo "$MATRIX_CONTEXT"
